### ISSUE TITLE
Unable to connect to ES endpoint using the sample docker-compose.yml file

### ISSUE THREAD

**Issue by SohamChakraborty** [opendistro-for-elasticsearch/community#117]
Hi,

I am trying opendistro using the docker-compose installation method documented here: https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/#sample-docker-compose-file

I  created the docker-compose.yml file as is and then run `sudo docker-compose up -d`, which starts all the containers. The only difference I have with the docker-compose.yml file and my compose file is that instead of using 1.1.0 image, I am using 0.9.0 image.

```
$ sudo docker-compose ps
   Name                  Command               State                            Ports                          
---------------------------------------------------------------------------------------------------------------
odfe-kibana   /usr/local/bin/kibana-docker     Up      0.0.0.0:5601->5601/tcp                                  
odfe-node1    /usr/local/bin/docker-entr ...   Up      0.0.0.0:9200->9200/tcp, 9300/tcp, 0.0.0.0:9600->9600/tcp
odfe-node2    /usr/local/bin/docker-entr ...   Up      9200/tcp, 9300/tcp, 9600/tcp     

$ sudo docker ps --no-trunc
CONTAINER ID                                                       IMAGE                                              COMMAND                                           CREATED             STATUS              PORTS                                                      NAMES
13edcd4727d5d5073532e5a64be6d6406fbe98532f2349d7d97903c49ba8732c   amazon/opendistro-for-elasticsearch:0.9.0          "/usr/local/bin/docker-entrypoint.sh eswrapper"   2 minutes ago       Up About a minute   9200/tcp, 9300/tcp, 9600/tcp                               odfe-node2
18096031ebf1659613cfd466c0db904470d0046c6917aa8b0fa24722a3968e3a   amazon/opendistro-for-elasticsearch:0.9.0          "/usr/local/bin/docker-entrypoint.sh eswrapper"   2 minutes ago       Up About a minute   0.0.0.0:9200->9200/tcp, 0.0.0.0:9600->9600/tcp, 9300/tcp   odfe-node1
3782eed0d1b834c1533d5a8036231bec2aeb97e0603a3f65645d10009d109fb1   amazon/opendistro-for-elasticsearch-kibana:0.9.0   "/usr/local/bin/kibana-docker"                    2 minutes ago       Up About a minute   0.0.0.0:5601->5601/tcp       
```
Then trying to curl the endpoint:

```
$ curl -k -vv -XGET https://localhost:9200/_cat/nodes?v -u admin:admin --insecure
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9200 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* ignoring certificate verify locations due to disabled peer verification
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:9200 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:9200 
```

I am also getting logs like this:

```
odfe-kibana   | {"type":"log","@timestamp":"2019-09-19T12:49:31Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: https://odfe-node1:9200/"}
odfe-kibana   | {"type":"log","@timestamp":"2019-09-19T12:49:31Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
odfe-kibana   | {"type":"log","@timestamp":"2019-09-19T12:49:34Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: https://odfe-node1:9200/"}
odfe-kibana   | {"type":"log","@timestamp":"2019-09-19T12:49:34Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
odfe-kibana   | {"type":"log","@timestamp":"2019-09-19T12:49:36Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: https://odfe-node1:9200/"}
odfe-kibana   | {"type":"log","@timestamp":"2019-09-19T12:49:36Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
```

Any suggestions? Am I missing something that is documented somewhere?

**Comment by aetter** [comment]
Hi @SohamChakraborty, ES 7.x uses different discovery settings than 6.x. Try the following, which is from the [0.9.0 docs](https://github.com/opendistro/for-elasticsearch-docs/releases):

```yml
version: '3'
services:
  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:0.9.0
    container_name: odfe-node1
    environment:
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - odfe-net
  odfe-node2:
    image: amazon/opendistro-for-elasticsearch:0.9.0
    container_name: odfe-node2
    environment:
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.zen.ping.unicast.hosts=odfe-node1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - odfe-data2:/usr/share/elasticsearch/data
    networks:
      - odfe-net
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:0.9.0
    container_name: odfe-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://odfe-node1:9200
      ELASTICSEARCH_HOSTS: https://odfe-node1:9200
    networks:
      - odfe-net

volumes:
  odfe-data1:
  odfe-data2:

networks:
  odfe-net:
```
