### ISSUE TITLE
Not able to set enforce_hostname_verification:true in Kubernetes

### ISSUE THREAD

**Issue by isaacnc** [opendistro-for-elasticsearch/community#130]
I have a service
```
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: bseg-es-test
  labels:
    component: elasticsearch
    role: master
spec:
  selector:
    component: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  clusterIP: None # Don't allocate a fixed IP address
  publishNotReadyAddresses: true
```

and a configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |-
    cluster:
      name: ${CLUSTER_NAME}
    node:
      master: ${NODE_MASTER}
      data: ${NODE_DATA}
      name: ${NODE_NAME}
      ingest: ${NODE_INGEST}
      max_local_storage_nodes: 1
      attr.box_type: hot

    processors: ${PROCESSORS:1}

    network.host: ${NETWORK_HOST}

    path:
      data: /usr/share/elasticsearch/data
      logs: /usr/share/elasticsearch/logs

    http:
      compression: true

    discovery:
      seed_hosts: ["es-master-0.elasticsearch.es-test.svc.k8s-dc.example.co.nz","es-master-1.elasticsearch.es-test.svc.k8s-dc.example.co.nz","es-master-2.elasticsearch.es-test.svc.k8s-dc.example.co.nz","es-master-0","es-master-1","es-master-2"]
      zen:
        minimum_master_nodes: ${NUMBER_OF_MASTERS}

    cluster.initial_master_nodes:
      - es-master-0.elasticsearch.es-test.svc.k8s-dc.example.co.nz
      - es-master-1.elasticsearch.es-test.svc.k8s-dc.example.co.nz
      - es-master-2.elasticsearch.es-test.svc.k8s-dc.example.co.nz
      - es-master-0
      - es-master-1
      - es-master-2

    # TLS Configuration Transport Layer
    opendistro_security.ssl.transport.pemcert_filepath: elk-crt.pem
    opendistro_security.ssl.transport.pemkey_filepath: elk-key.key
    opendistro_security.ssl.transport.pemtrustedcas_filepath: elk-root-ca.pem
    opendistro_security.ssl.transport.pemkey_password: ${TRANSPORT_TLS_PEM_PASS}
    opendistro_security.ssl.transport.enforce_hostname_verification: true

    # TLS Configuration REST Layer
    opendistro_security.ssl.http.enabled: true
    opendistro_security.ssl.http.pemcert_filepath: elk-crt.pem
    opendistro_security.ssl.http.pemkey_filepath: elk-key.key
    opendistro_security.ssl.http.pemtrustedcas_filepath: elk-root-ca.pem
    opendistro_security.ssl.http.pemkey_password: ${HTTP_TLS_PEM_PASS}

    # Demo Certificate Option Disabled
    opendistro_security.allow_unsafe_democertificates: false

    opendistro_security.allow_default_init_securityindex: true

    # Certificate to change the the Security plugin configuration
    opendistro_security.authcz.admin_dn:
    - elasticsearch-admin.es-test.svc.k8s-dc.example.co.nz,OU=Technology,O=Example NZ,L=Auckland,ST=Auckland,C=NZ

    # Identify inter-cluster requests
    opendistro_security.nodes_dn:
    - elasticsearch.es-test.svc.k8s-dc.example.co.nz,OU=Technology,O=Example NZ,L=Auckland,ST=Auckland,C=NZ
```

However masters are trying to form a cluster based on IP
```[2019-10-24T02:18:52,241][ERROR][c.a.o.s.s.t.OpenDistroSecuritySSLNettyTransport] [es-master-1] SSL Problem No subject alternative names matching IP address 172.32.29.142 found
javax.net.ssl.SSLHandshakeException: No subject alternative names matching IP address 172.32.29.142 found
```

Hence why I cannot set hostname verification to true
