### ISSUE TITLE
Can't get SAML working with GSuites

### ISSUE THREAD

**Issue by AlexShuraits** [opendistro-for-elasticsearch/community#172]
Hi,
I am trying to enable SAML auth in my Kubernetes Opendistro Cluster deployed with helm chart from this repository.
I have mounted the idp metadata file by editing the chart (It's not supported yet)
kibana.yml
```yaml
opendistro_security.auth.type: "saml"
server.xsrf.whitelist: ["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout"]
```
security-config.yml
```yaml
    authc:
      basic_internal_auth_domain:
        enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
      saml_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_file: idp-metadata.xml
              entity_id: https://accounts.google.com/o/saml2?idpid=xxxxxxxxx
            sp:
              entity_id: kibana-saml
            kibana_url: https://kibana.company.com/
            subject_key: nameid:persistent
            roles_key: groups
            exchange_key: 'yQffFcJtJf..........Jgx75GR7CN4'
        authentication_backend:
          type: noop
```
Can't get it working.
I have googled issues and tried different variations of config.
According the helm chart, the security config is mounted only to the master node, I have enabled it also on the client node because Kibana is communicating with it. 
I am not getting any error in logs, just:
**SAML configuration error
Something went wrong while retrieving the SAML configuration, please check your settings.**
in Kibana UI.
It doesn't redirect to the IDP, just getting back to see this error
Please suggest is it possible to get working?
