### ISSUE TITLE
ES stack can't start using OD plugins

### ISSUE THREAD

**Issue by malcolm061990** [opendistro-for-elasticsearch/community#177]
Hi all.
I am trying to use the Security plugin of Opendistro in existing ES cluster version 7.6.1 (not opendistro, just ES) in kubernetes.
The existing ES cluster works great with x-pack, but I want to use alerting of Opendistro that requires disabling x-pack and some other actions to do.
I installed alerting, security and job-scheduler plugins into ES successfully.
I followed the the steps in the link https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/.
And I use the yaml file to deploy the stack:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-logging
  name: elasticsearch-config
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |-
    # TLS Configuration Transport Layer
    opendistro_security.ssl.transport.pemcert_filepath: /usr/share/elasticsearch/config/node.pem
    opendistro_security.ssl.transport.pemkey_filepath: /usr/share/elasticsearch/config/node-key.pem
    opendistro_security.ssl.transport.pemtrustedcas_filepath: /usr/share/elasticsearch/config/root-ca.pem
    # opendistro_security.ssl.transport.pemkey_password: ${TRANSPORT_TLS_PEM_PASS}
    opendistro_security.ssl.transport.enforce_hostname_verification: false

     # Demo Certificate Option Disabled (- CN=admin,OU=SSL,O=DM,L=Test,C=AE)
    opendistro_security.allow_unsafe_democertificates: false
    opendistro_security.allow_default_init_securityindex: false
    opendistro_security.authcz.admin_dn:
      - CN=admin
      - CN=instance
    opendistro_security.nodes_dn:
      - 'CN=es-cluster*'
      - CN=instance

    opendistro_security.audit.type: internal_elasticsearch
    opendistro_security.enable_snapshot_restore_privilege: true
    opendistro_security.check_snapshot_restore_write_privileges: true
    opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
    cluster.routing.allocation.disk.threshold_enabled: false
    opendistro_security.audit.config.disabled_rest_categories: NONE
    opendistro_security.audit.config.disabled_transport_categories: NONE

  logging.yml: |-
    # you can override this using by setting a system property, for example -Des.logger.level=DEBUG
    es.logger.level: INFO
    rootLogger: ${es.logger.level}, console
    logger:
      # log action execution errors for easier debugging
      action: DEBUG
      # reduce the logging for aws, too much is logged under the default INFO
      com.amazonaws: WARN
    appender:
      console:
        type: console
        layout:
          type: consolePattern
          conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-logging
  name: elasticsearch-auth
  labels:
    app: elasticsearch
data:
  config.yml: |-
    ---
    _meta:
      type: "config"
      config_version: 2

    config:
      dynamic:
        http:
          anonymous_auth_enabled: false
          xff:
            enabled: false
            internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
            #internalProxies: '.*' # trust all internal proxies, regex pattern
            #remoteIpHeader:  'x-forwarded-for'
            ###### see https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html for regex help
            ###### more information about XFF https://en.wikipedia.org/wiki/X-Forwarded-For
            ###### and here https://tools.ietf.org/html/rfc7239
            ###### and https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html#Remote_IP_Valve
        authc:
          basic_internal_auth_domain:
            description: "Authenticate via HTTP Basic against internal users database"
            http_enabled: true
            transport_enabled: true
            order: 4
            http_authenticator:
              type: basic
              challenge: true
            authentication_backend:
              type: intern
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-logging
  name: elasticsearch-users
  labels:
    app: elasticsearch
data:
  config.yml: |-
    ---
    # This is the internal user database
    # The hash value is a bcrypt hash and can be generated with plugin/tools/hash.sh

    _meta:
      type: "internalusers"
      config_version: 2

    # Define your internal users here

    admin:
      hash: "$2y$12$p.Po3x.UjRiiL3KRuzz5CuDgI/amcFg0x9GVwkARdcNYISuLZd4Bq"
      reserved: true
      backend_roles:
      - "admin"
      description: "Admin user"

    ## Demo users

    kibanaserver:
      hash: "$2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H."
      reserved: true
      description: "Demo kibanaserver user"

    kibanaro:
      hash: "$2a$12$JJSXNfTowz7Uu5ttXfeYpeYE0arACvcwlPBStB1F.MI7f0U9Z4DGC"
      reserved: false
      backend_roles:
      - "kibanauser"
      - "readall"
      attributes:
        attribute1: "value1"
        attribute2: "value2"
        attribute3: "value3"
      description: "Demo kibanaro user"

    logstash:
      hash: "$2a$12$u1ShR4l4uBS3Uv59Pa2y5.1uQuZBrZtmNfqB3iM/.jL0XoV9sghS2"
      reserved: false
      backend_roles:
      - "logstash"
      description: "Demo logstash user"

    readall:
      hash: "$2a$12$ae4ycwzwvLtZxwZ82RmiEunBbIPiAmGZduBAjKN0TXdwQFtCwARz2"
      reserved: false
      backend_roles:
      - "readall"
      description: "Demo readall user"

    snapshotrestore:
      hash: "$2y$12$DpwmetHKwgYnorbgdvORCenv4NAK8cPUg8AI6pxLCuWf/ALc0.v7W"
      reserved: false
      backend_roles:
      - "snapshotrestore"
      description: "Demo snapshotrestore user"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kube-logging
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: kube-logging
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      serviceAccountName: elasticsearch
      containers:
      - name: elasticsearch
        image: SOME_REGISTRY/cis/elasticsearch-opendistro:SOME_VERSION
        resources:
            limits:
              cpu: 900m
            requests:
              cpu: 100m
        ports:
        - containerPort: 9200
          name: rest
        - containerPort: 9300
          name: inter-node
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
        - mountPath: /usr/share/elasticsearch/config/logging.yml
          name: config
          subPath: logging.yml
        - mountPath: /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
          name: auth
          subPath: config.yml
        - mountPath: /usr/share/elasticsearch/config/node.pem
          name: certs
          subPath: node.pem
          readOnly: true
        - mountPath: /usr/share/elasticsearch/config/node-key.pem
          name: certs
          subPath: node-key.pem
          readOnly: true
        - mountPath: /usr/share/elasticsearch/config/root-ca.pem
          name: certs
          subPath: root-ca.pem
          readOnly: true
        - mountPath: /usr/share/elasticsearch/config/admin.pem
          name: certs
          subPath: admin.pem
          readOnly: true
        - mountPath: /usr/share/elasticsearch/config/admin-key.pem
          name: certs
          subPath: admin-key.pem
          readOnly: true
        - mountPath: /usr/share/elasticsearch/config/admin-root-ca.pem
          name: certs
          subPath: admin-root-ca.pem
          readOnly: true
        env:
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch"
          - name: cluster.initial_master_nodes
            value: "es-cluster-0,es-cluster-1,es-cluster-2"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: xpack.security.enabled
            value: "false"
          - name: xpack.ml.enabled
            value: "false"
          - name: logger.org.elasticsearch.discovery
            value: "TRACE"
          - name: JAVA_HOME
            value: /usr/share/elasticsearch/jdk
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      volumes:
        - name: config
          configMap:
            defaultMode: 0644
            name: elasticsearch-config
        - name: auth
          configMap:
            defaultMode: 0644
            name: elasticsearch-auth
        - name: certs
          secret:
            defaultMode: 0644
            secretName: elasticsearch-tls-data
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: STORAGE_CLASS
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-logging
  name: elasticsearch
  labels:
    app: elasticsearch
```

For some reason I can't reach the port 9300 in ES pod by service name and by their ip addresses.
The describe of service in k8s (it has thee endpoints, it's correct):
```
kubectl -n kube-logging describe svc elasticsearch
Name:              elasticsearch
Namespace:         kube-logging
Labels:            app=elasticsearch
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"elasticsearch"},"name":"elasticsearch","namespace":"kube...
Selector:          app=elasticsearch
Type:              ClusterIP
IP:                None
Port:              rest  9200/TCP
TargetPort:        9200/TCP
Endpoints:         10.20.0.57:9200,10.20.2.42:9200,10.20.2.55:9200
Port:              inter-node  9300/TCP
TargetPort:        9300/TCP
Endpoints:         10.20.0.57:9300,10.20.2.42:9300,10.20.2.55:9300
Session Affinity:  None
Events:            <none>
```
For example, I go to pod es-cluster-1 (10.20.0.57). I can ping itself by service hostname. It means that DNS works as expected. I can curl to port 9300 locally from pod to localhost. But I can't curl to port 9300 of service of elasticsearch.
```
ping es-cluster-1
PING es-cluster-1.elasticsearch.kube-logging.svc.cluster.local (10.20.0.57) 56(84) bytes of data.
64 bytes from es-cluster-1.elasticsearch.kube-logging.svc.cluster.local (10.20.0.57): icmp_seq=1 ttl=255 time=0.014 ms
64 bytes from es-cluster-1.elasticsearch.kube-logging.svc.cluster.local (10.20.0.57): icmp_seq=2 ttl=255 time=0.021 ms
^C
--- es-cluster-1.elasticsearch.kube-logging.svc.cluster.local ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1005ms
rtt min/avg/max/mdev = 0.014/0.017/0.021/0.005 ms
[root@es-cluster-1 elasticsearch]# ping es-cluster-2.elasticsearch.kube-logging.svc.cluster.local
PING es-cluster-2.elasticsearch.kube-logging.svc.cluster.local (10.20.2.42) 56(84) bytes of data.
64 bytes from es-cluster-2.elasticsearch.kube-logging.svc.cluster.local (10.20.2.42): icmp_seq=1 ttl=253 time=0.391 ms
64 bytes from es-cluster-2.elasticsearch.kube-logging.svc.cluster.local (10.20.2.42): icmp_seq=2 ttl=253 time=0.416 ms
^C
--- es-cluster-2.elasticsearch.kube-logging.svc.cluster.local ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.391/0.403/0.416/0.023 ms
[root@es-cluster-1 elasticsearch]# ping es-cluster-0.elasticsearch.kube-logging.svc.cluster.local
PING es-cluster-0.elasticsearch.kube-logging.svc.cluster.local (10.20.2.55) 56(84) bytes of data.
64 bytes from es-cluster-0.elasticsearch.kube-logging.svc.cluster.local (10.20.2.55): icmp_seq=1 ttl=253 time=0.378 ms
64 bytes from es-cluster-0.elasticsearch.kube-logging.svc.cluster.local (10.20.2.55): icmp_seq=2 ttl=253 time=0.457 ms
^C
--- es-cluster-0.elasticsearch.kube-logging.svc.cluster.local ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1012ms
rtt min/avg/max/mdev = 0.378/0.417/0.457/0.044 ms
[root@es-cluster-1 elasticsearch]# curl localhost:9300
curl: (52) Empty reply from server
[root@es-cluster-1 elasticsearch]# curl es-cluster-1.elasticsearch.kube-logging.svc.cluster.local:9300
curl: (7) Failed connect to es-cluster-1.elasticsearch.kube-logging.svc.cluster.local:9300; Connection refused
[root@es-cluster-1 elasticsearch]# 
[root@es-cluster-1 elasticsearch]# curl es-cluster-1.elasticsearch:9300
curl: (7) Failed connect to es-cluster-1.elasticsearch:9300; Connection refused
```
What's the reason?
After I can curl to other pods I can run securityadmin.sh to initialize the cluster using OD plugins. Please, help.

The logs of ES pod:
```
{"type": "server", "timestamp": "2020-05-13T10:05:25,830Z", "level": "DEBUG", "component": "o.e.d.PeerFinder", "cluster.name": "k8s-logs", "node.name": "es-cluster-0", "message": "Peer{transportAddress=10.20.0.57:9300, discoveryNode=null, peersRequestInFlight=false} connection failed", 
"stacktrace": ["org.elasticsearch.transport.ConnectTransportException: [][10.20.0.57:9300] connect_exception",
```
