### ISSUE TITLE
docker-compose container of opendistro not restarting automatically on exception

### ISSUE THREAD

**Issue by tapanhalani** [opendistro-for-elasticsearch/community#244]
I am running opendistro using docker-compose, with the following docker-compose.yml file:

```
version: '3'
services:
  opendistro-node:
    image: amazon/opendistro-for-elasticsearch
    network_mode: "host"
    container_name: opendistro
    restart: on-failure
    environment:
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - cluster.name=test-cluster
      - node.name=node-1.test-cluster.opendistro.internal
      - discovery.seed_hosts=node-0.test-cluster.opendistro.internal,node-1.test-cluster.opendistro.internal,node-2.test-cluster.opendistro.internal
      - cluster.initial_master_nodes=node-0.test-cluster.opendistro.internal,node-1.test-cluster.opendistro.internal,node-2.test-cluster.opendistro.internal
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m" # minimum and maximum Java heap size, recommend setting both to 75% of system RAM
      - network.host=node-1.test-cluster.opendistro.internal
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
```

Even after specifying `restart: on-failure` or `restart: always`, the container does not restart automatically when it encounters the following exception:

```
org.elasticsearch.bootstrap.StartupException: BindTransportException[Failed to resolve host [dm-1.beinformed-test-v3.opendistro.internal]]; nested: UnknownHostException[node-1.test-cluster.opendistro.internal: Name or service not known];
```

I checked this even with running a single container using "docker run" directly, but saw the same behaviour as above. What more needs to be configured to make "automatic restarts on failure" work?
