### ISSUE TITLE
Proxy auth not working - opendistroforelasticsearch-1.13.0

### ISSUE THREAD

**Issue by JindrichD** [opendistro-for-elasticsearch/community#252]
Hi, 
i can't manage to make the proxy auth working for elasticsearch 1.13.0. i have the ES configuration based on this document: https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/proxy/
to make things as simple as possible, i downloaded the tarball, unpacked it. left default elasticsearch.yml. edited the security plugin config.yml - especially enabled xff, internalProxies: '.*' and enabled proxy_auth_domain. this is my configuration in config.yml:

```
_meta: 
  type: "config" 
  config_version: 2 

config: 
  dynamic: 
    http: 
      anonymous_auth_enabled: false 
      xff: 
        enabled: true 
        internalProxies: '.*' # trust all internal proxies, regex pattern 
        remoteIpHeader:  'x-forwarded-for' 
    authc: 
      basic_internal_auth_domain: 
        description: "Authenticate via HTTP Basic against internal users database" 
        http_enabled: false 
        transport_enabled: false 
        order: 4 
        http_authenticator: 
          type: basic 
          challenge: true 
        authentication_backend: 
          type: intern   
      proxy_auth_domain: 
        description: "Authenticate via proxy" 
        http_enabled: true 
        transport_enabled: true 
        order: 1 
        http_authenticator: 
          type: proxy 
          challenge: false 
          config: 
            user_header: "x-proxy-user" 
            roles_header: "x-proxy-roles" 
        authentication_backend: 
          type: noop 
    authz:
```
so i as understand from the docs - the above should enable proxy based authorization, and particularly interesting headers are x-proxy-user and x-proxy-roles. and x-forwarded-for. so i ran curl command like this
```
curl -X GET "https://localhost:9200/_cat/nodes?v=true&pretty" --insecure  -H 'x-proxy-user: admin' -H 'x-proxy-roles: admin' -H 'x-forwarded-for: 127.0.0.1'
```
but i am getting `Unauthorized`

Is there anything that i am missing?

Many thanks!

jd
