### ISSUE TITLE
Installing Kibana plugins 

### ISSUE THREAD

**Issue by jvmlet** [opendistro-for-elasticsearch/community#39]
I'm trying to install different Kiabana plugins on top of running open distro Kiabana docker  container. They all fail with the same error , below is one the of attempts:

```
sh-4.2$ ./bin/kibana-plugin install https://github.com/johtani/analyze-api-ui-plugin/releases/download/6.5.4/analyze-api-ui-plugin-6.5.4.zip
Attempting to transfer from https://github.com/johtani/analyze-api-ui-plugin/releases/download/6.5.4/analyze-api-ui-plugin-6.5.4.zip
Transferring 1876039 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false
(node:282) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`

{"type":"log","@timestamp":"2019-04-03T06:01:07Z","tags":["info","optimize"],"pid":282,"message":"Optimizing and caching bundles for stateSessionStorageRedirect, status_page, timelion, kibana, analyze-api-ui-plugin, security-login, security-customerror, security-multitenancy, security-accountinfo, security-configuration and opendistro-alerting. This may take a few minutes"}
```

My `docker-compose.yml` :
```
version: '3'
services:
  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:0.7.1
    container_name: odfe-node1
    environment:
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - opendistro_security.ssl.http.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - odfe-net
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:0.7.1
    container_name: odfe-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: http://odfe-node1:9200
    networks:
      - odfe-net

volumes:
  odfe-data1:
  odfe-data2:

networks:
  odfe-net:
```
Please advise.
Thanks
